wip: first run at adding holoscan as a dependency
Goal was to experiment with wrapping some bits in holoscan operators

There's some issue finding "cuda/stream_ref"

[build] /opt/nvidia/holoscan/holoscan-linux-x86_64-2.8.0.1-archive/include/rmm/cuda_stream_view.hpp:22:10: fatal error: cuda/stream_ref: No such file or directory
[build]    22 | #include <cuda/stream_ref>

This file should be in cuda:
/usr/local/cuda-12.6/targets/x86_64-linux/include/cuda/stream_ref

That file should be in libcudacxx https://github.com/NVIDIA/cccl/blob/main/libcudacxx/include/cuda/version
On ubuntu 24.04 I am using cuda 12.6 and up to 12.8 is available. I have
libcu++-dev which is version 1.9.0-3.

https://nvidia.github.io/cccl/libcudacxx/releases.html shows that
stream_ref was made available in libcudacxx 2.2.0 which should have come
with cuda 12.3, so need to figure out a way to get a newer libcudacxx
than ubuntu provides, and also figure out if we can support older cuda
with this newer libcudacxx